name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: debian-trixie
    container:
      image: docker.io/library/node:24-trixie-slim@sha256:4fc981bf8dfc5e36e15e0cb73c5761a14cabff0932dcad1cf26cd3c3425db5d4
    steps:
      - name: Check out source code
        uses: https://code.forgejo.org/actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set up toolchain
        uses: https://code.forgejo.org/actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: '>=1.25.6'
      - name: Install dependencies
        run: |
          apt-get -y update
          apt-get -y install ca-certificates
          go install honnef.co/go/tools/cmd/staticcheck@latest
      - name: Build application
        run: |
          go build
      - name: Run static analysis
        run: |
          go vet
          staticcheck

  release:
    # IMPORTANT: This workflow step will not work without the Releases unit enabled!
    if: ${{ forge.ref == 'refs/heads/main' || startsWith(forge.event.ref, 'refs/tags/v') }}
    needs: [check]
    runs-on: debian-trixie
    container:
      image: docker.io/library/node:24-trixie-slim@sha256:4fc981bf8dfc5e36e15e0cb73c5761a14cabff0932dcad1cf26cd3c3425db5d4
    steps:
      - name: Check out source code
        uses: https://code.forgejo.org/actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set up toolchain
        uses: https://code.forgejo.org/actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: '>=1.25.6'
      - name: Install dependencies
        run: |
          apt-get -y update
          apt-get -y install ca-certificates
      - name: Build release assets
        # If you want more platforms to be represented, send a pull request.
        run: |
          set -x
          build() { GOOS=$1 GOARCH=$2 go build -o assets/git-pages-cli.$1-$2$3; }
          build windows amd64 .exe
          build windows arm64 .exe
          build linux   amd64
          build linux   arm64
          build darwin  arm64
      - name: Create release
        uses: https://code.forgejo.org/actions/forgejo-release@e7b60f9ae8d4bbf3ed4cc178e4656ce40eb67256 # v2.11.2
        with:
          tag: ${{ startsWith(forge.event.ref, 'refs/tags/v') && forge.ref_name || 'latest' }}
          release-dir: assets
          direction: upload
          override: true
          prerelease: ${{ !startsWith(forge.event.ref, 'refs/tags/v') }}

  package:
    if: ${{ forge.ref == 'refs/heads/main' || startsWith(forge.event.ref, 'refs/tags/v') }}
    needs: [check]
    runs-on: debian-trixie
    container:
      image: docker.io/library/node:24-trixie-slim@sha256:4fc981bf8dfc5e36e15e0cb73c5761a14cabff0932dcad1cf26cd3c3425db5d4
    steps:
      - name: Install dependencies
        run: |
          apt-get -y update
          apt-get -y install ca-certificates buildah qemu-user-binfmt
      - name: Check out source code
        uses: https://code.forgejo.org/actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Build container
        run: |
          printf '[storage]\ndriver="vfs"\nrunroot="/run/containers/storage"\ngraphroot="/var/lib/containers/storage"\n' | tee /etc/containers/storage.conf
          buildah build --arch=amd64 --tag=container:amd64
          buildah build --arch=arm64 --tag=container:arm64
          buildah manifest create container container:amd64 container:arm64
        env:
          BUILDAH_ISOLATION: chroot
      - if: ${{ forge.repository == 'git-pages/git-pages-cli' }}
        name: Push container to Codeberg
        run: |
          buildah login --authfile=/tmp/authfile.json \
            -u ${{ vars.PACKAGES_USER }} -p ${{ secrets.PACKAGES_TOKEN }} ${FORGE}
          buildah manifest push --authfile=/tmp/authfile.json \
            --all container "docker://${FORGE}/${{ forge.repository }}:${VER/v/}"
        env:
          FORGE: codeberg.org
          VER: ${{ startsWith(forge.event.ref, 'refs/tags/v') && forge.ref_name || 'latest' }}
      - if: ${{ forge.repository == 'git-pages/git-pages-cli' }}
        name: Push container to code.forgejo.org
        run: |
          buildah login --authfile=/tmp/authfile.json \
            -u ${{ vars.PACKAGES_USER }} -p ${{ secrets.CFO_PACKAGES_TOKEN }} ${FORGE}
          buildah manifest push --authfile=/tmp/authfile.json \
            --all container "docker://${FORGE}/${{ forge.repository }}:${VER/v/}"
        env:
          FORGE: code.forgejo.org
          VER: ${{ startsWith(forge.event.ref, 'refs/tags/v') && forge.ref_name || 'latest' }}
